version: '3.2'

services:
  server:
    image: ${DOCKER_REGISTRY:-52.17.169.90:5000}/roey/ node-js-nedb-excercise-server:${VERSION:-1.0}
    restart: unless-stopped
    ports:
      - 3000:3000

  client:
    image: ${DOCKER_REGISTRY:-52.17.169.90:5000}/roey/ node-js-nedb-excercise-client:${VERSION:-1.0}
    restart: unless-stopped
    ports:
      - 3001:3001
    depends_on:
      - server
